#!/bin/sh
#
# post installation setup of WordPress theme, plugins and options, idempotently

test "`id -un`" == www-data || {
    echo >&2 "`basename $0`: must run as www-data - abort"
    exit 1
}

# any error is fatal
set -e

# run wp with particular path
wpp() {
    wp --path=/var/www/html/wordpress "$@"
}

#
# THEME
#

# install and activate the desired theme, if any
test -n "$WORDPRESS_THEME" && {
    wpp theme is-installed "$WORDPRESS_THEME" || \
        wpp theme install "$WORDPRESS_THEME" && \
    wpp theme is-active "$WORDPRESS_THEME" || \
        wpp theme activate "$WORDPRESS_THEME"
}

#
# PLUGINS
#

# install and activate required plugins, if any
test -n "$WORDPRESS_PLUGINS" && for plugin in $WORDPRESS_PLUGINS; do
    wpp plugin is-installed $plugin || \
        wpp plugin install $plugin && \
    wpp plugin is-active $plugin || \
        wpp plugin activate $plugin
done

# local plugins from zipfiles
test -d "$WORDPRESS_PLUGINS_DIR" && for zipfile in `cd $WORDPRESS_PLUGINS_DIR; ls *.zip`; do
    # assume plugin name is zipfile name without version and .zip extension
    plugin=`echo $zipfile | sed -e 's/-[0-9.]*.zip'//`
    wpp plugin is-installed $plugin || \
        wpp plugin install $WORDPRESS_PLUGINS_DIR/$zipfile && \
    wpp plugin is-active $plugin || \
        wpp plugin activate $plugin
done

#
# OPTIONS
#

# set required options, if any
# option values may not contain double quote character, use &#34; instead
test -d "$WORDPRESS_OPTIONS_DIR" && for options_file in `ls -d $WORDPRESS_OPTIONS_DIR/*`; do
    exec <$options_file
    while IFS='=' read name value; do
        case "$name" in
            \#*) # ignore comment
                ;;
            *)
                wpp option update "$name" "$value"
                ;;
        esac
    done
done
